---
blank_issues_enabled: false
contact_links:
  - name: Support question ❓
    url: https://github.com/calebdw/phpstan-laravel/discussions/new
    about: Please open a new discussion instead. Thank you.
